<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('nationalities', function (Blueprint $table) {
            $table->id();
            $table->string('nationality')->unique();
            $table->timestamps();
        });

        // Insert a list of known nationalities
        $nationalities = [
            'Afghan',
            'Albanian',
            'Algerian',
            'American',
            'Andorran',
            'Angolan',
            'Antiguan and Barbudan',
            'Argentine',
            'Armenian',
            'Australian',
            'Austrian',
            'Azerbaijani',
            'Bahamian',
            'Bahraini',
            'Bangladeshi',
            'Barbadian',
            'Belarusian',
            'Belgian',
            'Belizean',
            'Beninese',
            'Bhutanese',
            'Bolivian',
            'Bosnian',
            'Botswanan',
            'Brazilian',
            'British',
            'Bruneian',
            'Bulgarian',
            'Burkinabé',
            'Burmese',
            'Burundian',
            'Cambodian',
            'Cameroonian',
            'Canadian',
            'Cape Verdean',
            'Central African',
            'Chadian',
            'Chilean',
            'Chinese',
            'Colombian',
            'Comorian',
            'Congolese (Congo-Brazzaville)',
            'Congolese (Congo-Kinshasa)',
            'Costa Rican',
            'Croatian',
            'Cuban',
            'Cypriot',
            'Czech',
            'Danish',
            'Djiboutian',
            'Dominican',
            'Dutch',
            'East Timorese',
            'Ecuadorean',
            'Egyptian',
            'Emirati',
            'Equatorial Guinean',
            'Eritrean',
            'Estonian',
            'Eswatini',
            'Ethiopian',
            'Fijian',
            'Finnish',
            'French',
            'Gabonese',
            'Gambian',
            'Georgian',
            'German',
            'Ghanaian',
            'Greek',
            'Grenadian',
            'Guatemalan',
            'Guinean',
            'Bissau-Guinean',
            'Guyanese',
            'Haitian',
            'Honduran',
            'Hungarian',
            'Icelandic',
            'Indian',
            'Indonesian',
            'Iranian',
            'Iraqi',
            'Irish',
            'Israeli',
            'Italian',
            'Ivorian',
            'Jamaican',
            'Japanese',
            'Jordanian',
            'Kazakh',
            'Kenyan',
            'Kiribati',
            'Kuwaiti',
            'Kyrgyz',
            'Lao',
            'Latvian',
            'Lebanese',
            'Lesotho',
            'Liberian',
            'Libyan',
            'Liechtensteiner',
            'Lithuanian',
            'Luxembourgish',
            'Malagasy',
            'Malawian',
            'Malaysian',
            'Maldivian',
            'Malian',
            'Maltese',
            'Marshallese',
            'Mauritanian',
            'Mauritian',
            'Mexican',
            'Micronesian',
            'Moldovan',
            'Monégasque',
            'Mongolian',
            'Montenegrin',
            'Moroccan',
            'Mozambican',
            'Namibian',
            'Nauruan',
            'Nepalese',
            'New Zealander',
            'Nicaraguan',
            'Nigerien',
            'Nigerian',
            'North Korean',
            'North Macedonian',
            'Norwegian',
            'Omani',
            'Pakistani',
            'Palauan',
            'Palestinian',
            'Panamanian',
            'Papua New Guinean',
            'Paraguayan',
            'Peruvian',
            'Filipino',
            'Polish',
            'Portuguese',
            'Qatari',
            'Romanian',
            'Russian',
            'Rwandan',
            'Saint Lucian',
            'Salvadoran',
            'Samoan',
            'San Marinese',
            'São Toméan',
            'Saudi',
            'Scottish',
            'Senegalese',
            'Serbian',
            'Seychellois',
            'Sierra Leonean',
            'Singaporean',
            'Slovak',
            'Slovene',
            'Solomon Islander',
            'Somali',
            'South African',
            'South Korean',
            'South Sudanese',
            'Spanish',
            'Sri Lankan',
            'Sudanese',
            'Surinamese',
            'Swazi',
            'Swedish',
            'Swiss',
            'Syrian',
            'Taiwanese',
            'Tajik',
            'Tanzanian',
            'Thai',
            'Togolese',
            'Tongan',
            'Trinidadian and Tobagonian',
            'Tunisian',
            'Turkish',
            'Turkmen',
            'Tuvaluan',
            'Ugandan',
            'Ukrainian',
            'Uruguayan',
            'Uzbek',
            'Vanuatuan',
            'Vatican',
            'Venezuelan',
            'Vietnamese',
            'Yemeni',
            'Zambian',
            'Zimbabwean',
        ];

        foreach ($nationalities as $nationality) {
            DB::table('nationalities')->insert(['nationality' => $nationality]);
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('nationalities');
    }
};